name: Release

# Controls when the workflow will run
on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Submodules
        run: git submodule update --init
      - name: Build
        run: TERM=dumb ./gradlew jar
      - name: Upload
        run: curl https://marketplace.pretix.eu/upload/ -u pretixscan-proxy:${{ secrets.PLUM_UPLOAD_TOKEN }} -F "version=$(git describe --tags --always --first-parent)" -F "file=@server/build/libs/server-$(git describe --tags --always --first-parent).jar"
